### PR TITLE
CSR templates: further fixes on ASN.1 definitions and the example; text improvements 

### PR DESCRIPTION
**Pull request by DDvO**
I just noticed and fixed here an inconsistency regarding the newly introduced tag in with my latest PR #27.
On this occasion also improved the formatting and removed a spurious `;` symbol in the ASN.1 module.

### CODE REVIEW

**Comment by DDvO** [comment]
Lacking proper ASN.1 tooling (at least on my side), 
it's not unlikely that there are further (more or less subtle) ASN.1 bugs.

At some point, all ASN.1 contents must be double-checked.

**Comment by DDvO** [comment]
> Lacking proper ASN.1 tooling (at least on my side), it's not unlikely that there are further (more or less subtle) ASN.1 bugs.
> 
> At some point, all ASN.1 contents must be double-checked.

I've just been able to perform such a check using a tool
and in this way found and fixed many mistakes.

**Comment by DDvO** [comment]
Moreover, improved the text of section 3.3, plus some minor tweaks on 3.2 and the IANA considerations.

**Comment by DDvO** [comment]
Ping @mcr

**Review by mcr — APPROVED** [review]

**Pull request merged**
